"use client";

import { FormEvent, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import Link from "next/link";
import { ArrowRight, Bot, CheckCircle2, CircleAlert, Gauge, Mail, MessageCircle, Sparkles, Target, TrendingUp } from "lucide-react";
import { getWhatsAppUrl, socialLinks } from "@/config/social";
import { calculateDiagnosis, type DiagnosisLocale } from "@/lib/business-diagnosis";
import { buildDiagnosisResult, DIAGNOSIS_RESULT_STORAGE_KEY, isDiagnosisResult, type DiagnosisResult, type DiagnosisResultCategory } from "@/lib/diagnosis-result";
import styles from "./DiagnosisResults.module.css";

const businessEmail = "info@nextprintnyc.com";
const labels = {
  en: {
    eyebrow: "YOUR AI BUSINESS DIAGNOSIS", title: "Your digital growth report", intro: "A practical view of what is working, where customers may be getting lost, and what to improve next.", score: "Digital Health Score", completed: "Completed", id: "Diagnosis ID", dashboard: "Score dashboard", dashboardText: "Your current performance across the areas measured in the diagnosis.", findings: "Key findings", findingsText: "The areas below have the greatest potential to improve your customer journey and conversion.", journey: "Customer journey gaps", journeyText: "See where prospects may lose momentum between discovery and becoming a customer.", plan: "Your recommended action plan", planText: "Prioritized from your lowest scores so you can focus on the changes with the highest impact.", services: "How Next Studio can help", before: "From disconnected to conversion-ready", beforeLabel: "Current friction", afterLabel: "With the right system", consultation: "Request a consultation", personalized: "Get my personalized plan", whatsapp: "Talk on WhatsApp", formTitle: "Receive your personalized plan", formText: "Share your contact details and our team will review this diagnosis with you.", name: "Full name", business: "Business name", email: "Email", phone: "Phone / WhatsApp", submit: "Send my diagnosis", successTitle: "Your request is ready to send.", success: "Your email app has opened with the diagnosis details. Send the email to deliver your request.", emptyTitle: "Complete the diagnosis to view your report", emptyText: "This page only displays real results generated by the AI Business Diagnosis. No diagnosis was found in this browser session.", start: "Start the diagnosis", strengths: "What is already working", issues: "Critical issues", opportunities: "Growth opportunities", goal: "Customer", noFindings: "No major gaps were detected in the measured areas. Focus on optimization and scale.", status: ["Strong", "Developing", "Needs attention", "Critical"], impact: "Expected impact", steps: "Recommended next steps",
  },
  es: {
    eyebrow: "TU DIAGNÓSTICO DE NEGOCIO CON IA", title: "Tu informe de crecimiento digital", intro: "Una visión práctica de lo que funciona, dónde puedes estar perdiendo clientes y qué conviene mejorar ahora.", score: "Puntuación de Salud Digital", completed: "Completado", id: "ID del diagnóstico", dashboard: "Panel de puntuación", dashboardText: "Tu desempeño actual en las áreas evaluadas por el diagnóstico.", findings: "Hallazgos principales", findingsText: "Estas áreas tienen el mayor potencial para mejorar el recorrido del cliente y la conversión.", journey: "Brechas en el recorrido del cliente", journeyText: "Observa dónde los prospectos pueden perder impulso entre descubrir tu negocio y convertirse en clientes.", plan: "Tu plan de acción recomendado", planText: "Priorizado según tus puntuaciones más bajas para enfocarte en los cambios de mayor impacto.", services: "Cómo puede ayudarte Next Studio", before: "De una experiencia desconectada a un sistema que convierte", beforeLabel: "Fricción actual", afterLabel: "Con el sistema correcto", consultation: "Solicitar una consulta", personalized: "Obtener mi plan personalizado", whatsapp: "Hablar por WhatsApp", formTitle: "Recibe tu plan personalizado", formText: "Comparte tus datos y nuestro equipo revisará este diagnóstico contigo.", name: "Nombre completo", business: "Nombre del negocio", email: "Email", phone: "Teléfono / WhatsApp", submit: "Enviar mi diagnóstico", successTitle: "Tu solicitud está lista para enviarse.", success: "Tu aplicación de correo se abrió con los detalles del diagnóstico. Envía el correo para entregar tu solicitud.", emptyTitle: "Completa el diagnóstico para ver tu informe", emptyText: "Esta página solo muestra resultados reales generados por el Diagnóstico de Negocio con IA. No encontramos un diagnóstico en esta sesión del navegador.", start: "Comenzar diagnóstico", strengths: "Lo que ya funciona", issues: "Problemas críticos", opportunities: "Oportunidades de crecimiento", goal: "Cliente", noFindings: "No se detectaron brechas importantes en las áreas evaluadas. Enfócate en optimizar y escalar.", status: ["Sólido", "En desarrollo", "Necesita atención", "Crítico"], impact: "Impacto esperado", steps: "Próximos pasos recomendados",
  },
} as const;

const categoryCopy = {
  website: { en: ["Website", "Create a clear, fast, conversion-focused experience.", "Conversion Website"], es: ["Página web", "Crear una experiencia clara, rápida y enfocada en conversión.", "Página web de conversión"] },
  googlePresence: { en: ["Google Presence", "Improve local discoverability when customers are ready to buy.", "Google Business Optimization"], es: ["Presencia en Google", "Mejorar la visibilidad local cuando el cliente está listo para comprar.", "Optimización de Google Business"] },
  socialMedia: { en: ["Social Media", "Build consistent trust and guide attention toward action.", "Digital Branding"], es: ["Redes sociales", "Construir confianza constante y dirigir la atención hacia una acción.", "Branding digital"] },
  leadGeneration: { en: ["Lead Generation", "Capture prospect information instead of losing anonymous visits.", "Lead Capture System"], es: ["Generación de prospectos", "Capturar los datos del prospecto en lugar de perder visitas anónimas.", "Sistema de captación de prospectos"] },
  automation: { en: ["Automation", "Reduce repetitive work and respond faster with connected workflows.", "AI & Business Automation"], es: ["Automatización", "Reducir tareas repetitivas y responder más rápido con flujos conectados.", "IA y automatización de negocio"] },
  customerFollowUp: { en: ["Customer Follow-Up", "Create a reliable process that moves leads toward a decision.", "CRM & Follow-Up"], es: ["Seguimiento al cliente", "Crear un proceso confiable que lleve al prospecto hacia una decisión.", "CRM y seguimiento"] },
  onlineReputation: { en: ["Online Reputation", "Strengthen trust with an intentional review strategy.", "Review Growth System"], es: ["Reputación online", "Fortalecer la confianza con una estrategia intencional de reseñas.", "Sistema de crecimiento de reseñas"] },
} as const;

type Key = DiagnosisResultCategory["key"];
const scoreStatus = (score: number) => score >= 80 ? 0 : score >= 60 ? 1 : score >= 40 ? 2 : 3;

export function DiagnosisResults({ locale }: { locale: DiagnosisLocale }) {
  const c = labels[locale];
  const [result, setResult] = useState<DiagnosisResult | null>(null);
  const [ready, setReady] = useState(false);
  const [sent, setSent] = useState(false);
  const formRef = useRef<HTMLElement>(null);
  useEffect(() => {
    let nextResult: DiagnosisResult | null = null;
    try {
      const raw = sessionStorage.getItem(DIAGNOSIS_RESULT_STORAGE_KEY);
      const parsed: unknown = raw ? JSON.parse(raw) : null;
      if (isDiagnosisResult(parsed)) {
        nextResult = parsed.locale === locale ? parsed : {
          ...buildDiagnosisResult({ locale, answers: parsed.answers, local: calculateDiagnosis(parsed.answers, locale), ai: null }),
          id: parsed.id,
          completedAt: parsed.completedAt,
        };
      }
    } catch { /* Invalid or unavailable session storage is handled by the empty state. */ }
    const frame = requestAnimationFrame(() => { setResult(nextResult); setReady(true); });
    return () => cancelAnimationFrame(frame);
  }, [locale]);
  const sorted = useMemo(() => [...(result?.categories ?? [])].sort((a, b) => a.score - b.score), [result]);
  const findings = sorted.filter(item => item.score < 80);
  const recommended = sorted.slice(0, 4);
  const diagnosisPath = locale === "es" ? "/es/diagnostico-ia" : "/en/ai-business-diagnosis";
  const contactPath = locale === "es" ? "/es/contacto" : "/en/contact";
  const whatsappMessage = locale === "es" ? `Hola, completé mi diagnóstico de negocio con IA${result ? ` (${result.id}, ${result.overallScore}/100)` : ""} y deseo revisar mi plan.` : `Hello, I completed my AI Business Diagnosis${result ? ` (${result.id}, ${result.overallScore}/100)` : ""} and would like to review my plan.`;
  const whatsappUrl = getWhatsAppUrl(whatsappMessage);
  if (!ready) return <main className={styles.page}><div className={styles.loading}><Bot/><span>Next Studio AI</span></div></main>;
  if (!result) return <main className={styles.page}><section className={styles.empty}><Bot/><p>NS AI BUSINESS DIAGNOSIS™</p><h1>{c.emptyTitle}</h1><span>{c.emptyText}</span><Link href={diagnosisPath}>{c.start}<ArrowRight/></Link></section></main>;
  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const fields = Array.from(data.entries()).map(([key, value]) => `${key}: ${value}`).join("\n");
    const scores = result.categories.map(item => `${categoryCopy[item.key][locale][0]}: ${item.score}/100`).join("\n");
    const body = `${fields}\n\nDiagnosis ID: ${result.id}\nCompleted: ${result.completedAt}\nLanguage: ${result.language}\nIndustry: ${result.industry ?? "—"}\nOverall Score: ${result.overallScore}/100\n\nCategory Scores:\n${scores}\n\nCritical Issues:\n${result.criticalIssues.join("\n")}\n\nRecommendations:\n${result.recommendations.join("\n")}`;
    const subject = locale === "es" ? `Plan personalizado — Diagnóstico ${result.id}` : `Personalized plan — Diagnosis ${result.id}`;
    setSent(true);
    window.location.href = `mailto:${businessEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };
  return <main className={styles.page}>
    <section className={styles.hero}><div className={styles.wrap}><div className={styles.heroCopy}><p>{c.eyebrow}</p><h1>{result.answers.businessName || c.title}</h1><h2>{c.title}</h2><span>{c.intro}</span><div className={styles.meta}><small>{c.id}<b>{result.id}</b></small><small>{c.completed}<b>{new Intl.DateTimeFormat(locale, { dateStyle: "medium" }).format(new Date(result.completedAt))}</b></small></div></div><div className={styles.scoreCard}><div className={styles.ring} style={{ "--score": `${result.overallScore * 3.6}deg` } as CSSProperties}><div><strong>{result.overallScore}</strong><span>/100</span></div></div><p>{c.score}</p><b className={styles[`status${scoreStatus(result.overallScore)}`]}>{c.status[scoreStatus(result.overallScore)]}</b></div></div></section>
    <section className={styles.section}><Heading icon={<Gauge/>} title={c.dashboard} text={c.dashboardText}/><div className={styles.scoreGrid}>{result.categories.map(item => <Score key={item.key} item={item} locale={locale}/>)}</div></section>
    <section className={`${styles.section} ${styles.tint}`}><Heading icon={<CircleAlert/>} title={c.findings} text={c.findingsText}/>{findings.length ? <div className={styles.findings}>{findings.map(item => <article key={item.key}><div><span>{item.score}/100</span><b className={styles[`status${scoreStatus(item.score)}`]}>{c.status[scoreStatus(item.score)]}</b></div><h3>{categoryCopy[item.key][locale][0]}</h3><p>{categoryCopy[item.key][locale][1]}</p></article>)}</div> : <p className={styles.noFindings}>{c.noFindings}</p>}<div className={styles.insights}><Insight title={c.strengths} items={result.strengths}/><Insight title={c.issues} items={result.criticalIssues}/><Insight title={c.opportunities} items={result.opportunities}/></div></section>
    <section className={styles.section}><Heading icon={<TrendingUp/>} title={c.journey} text={c.journeyText}/><div className={styles.journey}>{(["googlePresence","website","socialMedia","leadGeneration","customerFollowUp"] as Key[]).map(key => { const item=result.categories.find(x=>x.key===key); return <div key={key}><span className={item?styles[`dot${scoreStatus(item.score)}`]:styles.dot3}/><b>{categoryCopy[key][locale][0]}</b><small>{item?.score ?? 0}/100</small></div>})}<div><span className={styles.goalDot}/><b>{c.goal}</b><small>✓</small></div></div></section>
    <section className={`${styles.section} ${styles.tint}`}><Heading icon={<Target/>} title={c.plan} text={c.planText}/><div className={styles.plan}>{recommended.map((item, index) => <article key={item.key}><span>0{index + 1}</span><div><small>{c.impact}: {item.score < 40 ? c.status[3] : c.status[2]}</small><h3>{categoryCopy[item.key][locale][2]}</h3><p>{categoryCopy[item.key][locale][1]}</p></div></article>)}</div></section>
    <section className={styles.section}><Heading icon={<Sparkles/>} title={c.services}/><div className={styles.services}>{recommended.map(item => <article key={item.key}><Sparkles/><h3>{categoryCopy[item.key][locale][2]}</h3><p>{categoryCopy[item.key][locale][1]}</p></article>)}</div></section>
    <section className={styles.beforeAfter}><div><small>{c.beforeLabel}</small><p>{locale === "es" ? "Visibilidad aislada, tareas manuales y prospectos sin seguimiento." : "Disconnected visibility, manual tasks, and leads without follow-up."}</p></div><ArrowRight/><div><small>{c.afterLabel}</small><p>{locale === "es" ? "Una experiencia conectada que captura, acompaña y convierte." : "A connected experience that captures, nurtures, and converts."}</p></div></section>
    <section className={styles.cta}><div><p>NEXT STUDIO</p><h2>{locale === "es" ? "Convierte este diagnóstico en un plan de crecimiento." : "Turn this diagnosis into a growth plan."}</h2></div><div><Link href={contactPath}>{c.consultation}<ArrowRight/></Link><button type="button" onClick={() => formRef.current?.scrollIntoView({ behavior: "smooth" })}>{c.personalized}</button>{socialLinks.whatsapp && <a href={whatsappUrl} target="_blank" rel="noopener noreferrer"><MessageCircle/>{c.whatsapp}</a>}</div></section>
    <section className={styles.lead} ref={formRef}><div><Mail/><p>DIAGNOSIS {result.id}</p><h2>{c.formTitle}</h2><span>{c.formText}</span></div><form onSubmit={onSubmit}><label>{c.name}<input name="Full Name" required autoComplete="name"/></label><label>{c.business}<input name="Business Name" required defaultValue={result.answers.businessName} autoComplete="organization"/></label><label>{c.email}<input name="Email" type="email" required autoComplete="email"/></label><label>{c.phone}<input name="Phone / WhatsApp" type="tel" required autoComplete="tel"/></label><button type="submit">{c.submit}<ArrowRight/></button>{sent && <p className={styles.success}><CheckCircle2/>{c.successTitle} {c.success}</p>}</form></section>
  </main>;
}

function Heading({ icon, title, text }: { icon: React.ReactNode; title: string; text?: string }) { return <header className={styles.heading}><i>{icon}</i><div><h2>{title}</h2>{text && <p>{text}</p>}</div></header>; }
function Score({ item, locale }: { item: DiagnosisResultCategory; locale: DiagnosisLocale }) { const c=labels[locale]; const status=scoreStatus(item.score); return <article><div><h3>{categoryCopy[item.key][locale][0]}</h3><strong>{item.score}</strong></div><span><i className={styles[`bar${status}`]} style={{ width: `${item.score}%` }}/></span><small className={styles[`status${status}`]}>{c.status[status]}</small></article>; }
function Insight({ title, items }: { title: string; items: string[] }) { return <article><h3>{title}</h3>{items.slice(0, 5).map((item, index) => <p key={`${index}-${item}`}><CheckCircle2/>{item}</p>)}</article>; }
