"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import QRCode from "qrcode";
import { Download, Globe2, Link2, Mail, MapPin, MessageCircle, Phone, QrCode, RotateCcw, TextCursorInput, Upload, UserRound, Wifi } from "lucide-react";
import { qrContent, type QRFields, type QRType } from "@/lib/qr/content";
import { labels, qrCopy } from "@/content/qr-generator";
import type { Locale } from "@/types/locale";
import s from "./QRGenerator.module.css";

const types: { id: QRType; icon: typeof Globe2 }[] = [{id:"website",icon:Globe2},{id:"whatsapp",icon:MessageCircle},{id:"phone",icon:Phone},{id:"email",icon:Mail},{id:"wifi",icon:Wifi},{id:"text",icon:TextCursorInput},{id:"location",icon:MapPin},{id:"vcard",icon:UserRound}];
const defaults: QRFields = { url:"",country:"+1",phone:"",message:"",email:"",subject:"",ssid:"",password:"",security:"WPA",hidden:false,text:"",latitude:"",longitude:"",firstName:"",lastName:"",company:"",job:"",website:"",address:"",city:"",state:"",zip:"" };
const contrast = (a: string,b: string) => { const x=(h:string)=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)).reduce((p,v)=>p+v,0); return Math.abs(x(a)-x(b)); };

export function QRGenerator({locale}:{locale:Locale}) {
 const c=qrCopy[locale], l=labels[locale]; const [type,setType]=useState<QRType>("website"),[fields,setFields]=useState<QRFields>(defaults),[foreground,setForeground]=useState("#082851"),[background,setBackground]=useState("#ffffff"),[size,setSize]=useState("1024"),[style,setStyle]=useState("square"),[logo,setLogo]=useState<string | null>(null),[png,setPng]=useState(""),[svg,setSvg]=useState(""),[notice,setNotice]=useState(""); const input=useRef<HTMLInputElement>(null);
 const content=useMemo(()=>qrContent(type,fields),[type,fields]); const valid=Boolean(content); const update=(key:string,value:string|boolean)=>setFields(prev=>({...prev,[key]:value}));
 useEffect(()=>{ let active=true; if(!content)return; const options={errorCorrectionLevel:logo?"H" as const:"M" as const,margin:3,width:640,color:{dark:foreground,light:background}}; Promise.all([QRCode.toDataURL(content,options),QRCode.toString(content,{...options,type:"svg"})]).then(([data,vector])=>{if(active){setPng(data);setSvg(vector);}}).catch(()=>{if(active){setPng("");setSvg("");}}); return()=>{active=false;}; },[content,foreground,background,logo]);
 const download=(kind:"png"|"svg")=>{ if(!content)return; const name=`next-studio-qr-${type}.${kind}`; const a=document.createElement("a"); if(kind==="png"){ if(!png)return; a.href=png;} else {a.href=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));} a.download=name;a.click();if(kind==="svg")setTimeout(()=>URL.revokeObjectURL(a.href),100);setNotice(c.downloaded);};
 const reset=()=>{setType("website");setFields(defaults);setForeground("#082851");setBackground("#ffffff");setSize("1024");setStyle("square");setLogo(null);setNotice("");};
 const current=(...keys:string[])=> <>{keys.map(key=>{const title=key.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase()); if(key==="message"||key==="text"||key==="address") return <label key={key}>{title}<textarea value={String(fields[key]??"")} maxLength={key==="text"?500:undefined} onChange={e=>update(key,e.target.value)}/>{key==="text"&&<small>{String(fields.text??"").length}/500</small>}</label>; return <label key={key}>{title}<input type={key==="email"?"email":"text"} value={String(fields[key]??"")} onChange={e=>update(key,e.target.value)}/></label>;})}</>;
 const fieldsFor=()=>{switch(type){case"website":return current("url");case"whatsapp":return <><label>{locale==="en"?"Country code":"Código de país"}<input value={String(fields.country)} onChange={e=>update("country",e.target.value)} placeholder="+1 / +593"/></label>{current("phone","message")}</>;case"phone":return current("phone");case"email":return current("email","subject","message");case"wifi":return <><>{current("ssid","password")}</><label>{locale==="en"?"Security":"Seguridad"}<select value={String(fields.security)} onChange={e=>update("security",e.target.value)}><option value="WPA">WPA/WPA2</option><option value="WEP">WEP</option><option value="nopass">None</option></select></label><label className={s.check}><input type="checkbox" checked={Boolean(fields.hidden)} onChange={e=>update("hidden",e.target.checked)}/>{locale==="en"?"Hidden network":"Red oculta"}</label></>;case"text":return current("text");case"location":return <><>{current("latitude","longitude")}</><button className={s.location} type="button" onClick={()=>navigator.geolocation?.getCurrentPosition(p=>{update("latitude",String(p.coords.latitude));update("longitude",String(p.coords.longitude));},()=>setNotice(locale==="en"?"Location permission was not granted.":"No se concedió permiso de ubicación."))}>{c.useLocation}</button></>;case"vcard":return current("firstName","lastName","company","job","phone","email","website","address","city","state","zip","country");}};
 return <main><section className={s.hero}><div><b>{c.badge}</b><h1>{c.title}</h1><p>{c.desc}</p></div></section><section className={s.workspace}><div className={s.form}><h2>{c.setup}</h2><div className={s.types}>{types.map(({id,icon:Icon})=><button type="button" key={id} className={type===id?s.active:""} onClick={()=>{setType(id);setNotice("");}}><Icon size={18}/><span>{l[id]}</span></button>)}</div><div className={s.fields}>{fieldsFor()}</div><div className={s.custom}><h3>{c.customize}</h3><div className={s.twocol}><label>{c.foreground}<input type="color" value={foreground} onChange={e=>setForeground(e.target.value)}/></label><label>{c.background}<input type="color" value={background} onChange={e=>setBackground(e.target.value)}/></label><label>{c.style}<select value={style} onChange={e=>setStyle(e.target.value)}><option value="square">Square</option><option value="rounded">Rounded</option><option value="dots">Dots</option></select></label><label>{c.size}<select value={size} onChange={e=>setSize(e.target.value)}><option>512</option><option>1024</option><option>2048</option></select></label></div>{contrast(foreground,background)<100&&<p className={s.warning}>{c.contrast}</p>}<div className={s.logo}><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(file)setLogo(URL.createObjectURL(file));}}/><button type="button" onClick={()=>input.current?.click()}><Upload size={16}/>{c.logo}</button>{logo&&<button type="button" onClick={()=>setLogo(null)}>{c.remove}</button>}</div></div></div><aside className={s.preview}><h2>{c.preview}</h2>{valid&&png?<><div className={`${s.qr} ${style==="rounded"?s.rounded:style==="dots"?s.dots:""}`}><img src={png} alt={`${l[type]} QR`} />{logo&&<img className={s.logoImage} src={logo} alt=""/>}</div><p>{l[type]} QR</p><div className={s.actions}><button type="button" onClick={()=>download("png")}><Download size={16}/>{c.png}</button><button type="button" onClick={()=>download("svg")}><Download size={16}/>{c.svg}</button><button type="button" className={s.secondary} onClick={()=>navigator.clipboard?.writeText(content ?? "").then(()=>setNotice(c.copied))}><Link2 size={16}/>{c.copy}</button><button type="button" className={s.secondary} onClick={reset}><RotateCcw size={16}/>{c.reset}</button></div></>:<div className={s.empty}><QrCode size={48}/><p>{c.empty}</p></div>}{notice&&<p className={s.notice}>{notice}</p>}</aside></section><section className={s.banner}><h2>{c.bannerTitle}</h2><p>{c.bannerDesc}</p><a href={`/${locale}`}>{c.bannerCta}</a></section></main>;
}
