import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bot, ChevronDown, CreditCard, Globe2, Menu, Rocket, Sparkles } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { ecuadorMarket, type EcuadorLocale } from "@/config/markets";
import styles from "./EcuadorHome.module.css";

type Copy = { nav: string[]; eyebrow: string; title: React.ReactNode; lead: string; primary: string; secondary: string; solutions: string; solutionTitle: string; plans: string; plansTitle: string; programs: string; programsText: string; evolution: string; evolutionTitle: string; contact: string; contactTitle: string; contactText: string; contactCta: string; monthly: string; setup: string; card: string; language: string; menu: string; };
const copy: Record<EcuadorLocale, Copy> = {
  es: { nav:["Inicio","Soluciones","Páginas Web","Apps & Software","IA & Automatización","Tarjeta Digital","Precios","Nosotros","Contacto"],eyebrow:"Soluciones digitales para Ecuador",title:<>Tu negocio, listo para <span>crecer online.</span></>,lead:"Páginas web, aplicaciones, automatización e inteligencia artificial creadas para las empresas que mueven Ecuador.",primary:"Ver soluciones",secondary:"Solicitar información",solutions:"Soluciones",solutionTitle:"Una presencia digital que trabaja por tu negocio.",plans:"Precios Ecuador",plansTitle:"Empieza con la solución adecuada para hoy.",programs:"Programas Gratis",programsText:"Explora herramientas gratuitas ya disponibles dentro del ecosistema Next Studio.",evolution:"El ecosistema",evolutionTitle:"Crece a tu ritmo, sin cambiar de equipo.",contact:"Hablemos",contactTitle:"Construyamos el próximo paso de tu negocio.",contactText:"Cuéntanos qué quieres lograr y te ayudaremos a elegir la solución correcta.",contactCta:"Solicitar información",monthly:"mensual",setup:"Configuración",card:"Tarjeta Digital",language:"English",menu:"Menú" },
  en: { nav:["Home","Solutions","Websites","Apps & Software","AI & Automation","Digital Card","Pricing","About","Contact"],eyebrow:"Digital solutions for Ecuador",title:<>Your business, ready to <span>grow online.</span></>,lead:"Websites, apps, automation, and artificial intelligence built for the companies moving Ecuador forward.",primary:"Explore solutions",secondary:"Request information",solutions:"Solutions",solutionTitle:"A digital presence that works for your business.",plans:"Ecuador pricing",plansTitle:"Start with the solution that fits today.",programs:"Free Programs",programsText:"Explore free tools already available in the Next Studio ecosystem.",evolution:"The ecosystem",evolutionTitle:"Grow at your own pace, with one team.",contact:"Let's talk",contactTitle:"Let's build your business's next step.",contactText:"Tell us what you want to achieve and we'll help you choose the right solution.",contactCta:"Request information",monthly:"monthly",setup:"Setup",card:"Digital Business Card",language:"Español",menu:"Menu" },
};
const anchors = ["home","websites","apps","automation","digital-card","programs","pricing","contact"];

export function EcuadorHome({ locale }: { locale: EcuadorLocale }) { const t=copy[locale]; const alternate=locale==="es"?"en":"es"; const localize=(es:string,en:string)=>locale==="es"?es:en; const paths=locale==="es"?["","soluciones","paginas-web","apps","ia-automatizacion","tarjeta-digital","precios","nosotros","contacto"]:["","solutions","websites","apps","ai-automation","digital-card","pricing","about","contact"]; const solutionData: [LucideIcon,string,string][]=[[Globe2,localize("Páginas Web","Websites"),localize("Sitios modernos y claros que generan confianza y convierten visitas en conversaciones.","Modern, clear sites that build trust and turn visits into conversations.")],[CreditCard,localize("Tarjeta Digital","Digital Business Card"),localize("Comparte tu contacto, servicios y enlaces en una tarjeta digital profesional.","Share your contact, services, and links in one polished digital card.")],[Rocket,localize("Apps y Herramientas","Apps & Tools"),localize("Herramientas útiles y aplicaciones a la medida de cómo trabaja tu equipo.","Useful tools and custom apps designed around the way your team works.")],[Bot,"AI & Automation",localize("Automatiza las tareas repetitivas y gana más tiempo para crecer.","Automate repetitive work and give your business more time to grow.")]]; return <main className={styles.page}>
  <header className={styles.header}><Link href={`/ec/${locale}`} className={styles.logo} aria-label="Next Studio Ecuador"><Image src="/images/brand/next-studio-logo.png" alt="Next Studio" width={116} height={70} priority /></Link><nav aria-label="Ecuador navigation">{t.nav.map((item,index)=><Link key={item} href={`/ec/${locale}${paths[index]?`/${paths[index]}`:""}`}>{item}</Link>)}</nav><div className={styles.switchers}><span className={styles.country}>🇪🇨 Ecuador</span><Link href={`/ec/${alternate}`} className={styles.locale}>🇪🇨 Ecuador | {locale==="es"?"Español":"English"}<ChevronDown size={14}/></Link></div><span className={styles.mobileMenu}><Menu size={18}/>{t.menu}</span></header>
  <section id="home" className={styles.hero}><div className={styles.heroCopy}><p className={styles.kicker}>🇪🇨 {t.eyebrow}</p><h1>{t.title}</h1><p>{t.lead}</p><div className={styles.actions}><a className={styles.primary} href="#websites">{t.primary}<ArrowRight size={18}/></a><a className={styles.secondary} href="#contact">{t.secondary}</a></div></div><div className={styles.visual}><div className={styles.orb}/><Image src="/images/ecuador/ecuador-hero.png" alt={localize("Soluciones digitales para un negocio en Ecuador","Digital solutions for an Ecuadorian business")} fill priority sizes="(max-width: 840px) 100vw, 53vw"/></div></section>
  <section id="websites" className={styles.section}><p className={styles.kicker}>{t.solutions}</p><h2>{t.solutionTitle}</h2><div className={styles.solutionGrid}>{solutionData.map(([Icon,title,text],index)=><article id={anchors[index+1]} key={title}><span><Icon size={24}/></span><h3>{title}</h3><p>{text}</p><a href="#contact">{localize("Conocer más","Learn more")}<ArrowRight size={15}/></a></article>)}</div></section>
  <section id="pricing" className={`${styles.section} ${styles.pricing}`}><p className={styles.kicker}>{t.plans}</p><h2>{t.plansTitle}</h2><div className={styles.priceGrid}>{ecuadorMarket.plans.map((plan,index)=><article className={index===2?styles.featured:""} key={plan.id}>{index===2&&<b>{localize("Más elegido","Most popular")}</b>}<h3>{plan.name}</h3><p>{t.setup}</p><strong>{plan.setup}</strong><p>{t.monthly}</p><strong>{plan.monthly}</strong><a href="#contact">{t.contactCta}<ArrowRight size={15}/></a></article>)}</div><div id="digital-card" className={styles.cardPrice}><CreditCard size={24}/><div><strong>{t.card}</strong><span>{localize("Una sola vez","One-time")}</span></div><b>{ecuadorMarket.digitalCard}</b><a href="#contact">{t.contactCta}<ArrowRight size={15}/></a></div></section>
  <section id="apps" className={styles.ecosystem}><div><p className={styles.kicker}>{t.evolution}</p><h2>{t.evolutionTitle}</h2><p>{localize("Desde una app gratuita hasta una plataforma a medida: cada solución prepara a tu negocio para la siguiente etapa.","From a free app to a custom platform: every solution prepares your business for the next stage.")}</p></div><ol>{["Free App",t.card,"Website Basic","Business","Business Pro","AI Business","Custom Platform"].map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol></section>
  <section id="programs" className={styles.programs}><div><Sparkles size={24}/><p className={styles.kicker}>{t.programs}</p><h2>{localize("Herramientas útiles para empezar.","Useful tools to get started.")}</h2><p>{t.programsText}</p></div><Link href={locale==="es"?"/es/programas-gratis":"/en/free-programs"}>{localize("Ver programas","View programs")}<ArrowRight size={17}/></Link></section>
  <section id="contact" className={styles.contact}><p className={styles.kicker}>{t.contact}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><a className={styles.primary} href="mailto:info@nextprintnyc.com?subject=Next%20Studio%20Ecuador">{t.contactCta}<ArrowRight size={18}/></a></section><footer className={styles.footer}><Image src="/images/brand/next-studio-logo.png" alt="Next Studio" width={112} height={68}/><span>© {new Date().getFullYear()} Next Studio · Ecuador</span><Link href={`/ec/${alternate}`}>{t.language}</Link></footer></main>; }
