import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bot, BriefcaseBusiness, Check, CircleUserRound, CreditCard, Globe2, Mail, MessageCircle, MonitorSmartphone, Phone, QrCode, Rocket, Save, Share2, ShieldCheck, Sparkles, TrendingUp, UserRoundCog, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { ecuadorMarket, type EcuadorLocale } from "@/config/markets";
import { EcuadorLeadForm } from "./EcuadorLeadForm";
import styles from "./EcuadorHome.module.css";
import ps from "./EcuadorHomePricing.module.css";
import { BrandHeader } from "@/components/design-system/navigation/BrandHeader";
import { BrandFooter } from "@/components/design-system/navigation/BrandFooter";

type Copy = { nav: string[]; eyebrow: string; title: React.ReactNode; lead: string; primary: string; secondary: string; solutions: string; solutionTitle: string; plans: string; plansTitle: string; programs: string; programsText: string; evolution: string; evolutionTitle: string; contact: string; contactTitle: string; contactText: string; contactCta: string; monthly: string; setup: string; card: string; language: string; menu: string; };
const copy: Record<EcuadorLocale, Copy> = {
  es: { nav:["Inicio","Soluciones","Páginas Web","Apps & Software","IA & Automatización","Tarjeta Digital","Precios","Nosotros","Contacto"],eyebrow:"Soluciones digitales para Ecuador",title:<>Tu negocio, listo para <span>crecer online.</span></>,lead:"Páginas web, aplicaciones, automatización e inteligencia artificial creadas para las empresas que mueven Ecuador.",primary:"Ver soluciones",secondary:"Solicitar información",solutions:"Soluciones",solutionTitle:"Una presencia digital que trabaja por tu negocio.",plans:"Precios Ecuador",plansTitle:"Empieza con la solución adecuada para hoy.",programs:"Programas Gratis",programsText:"Explora herramientas gratuitas ya disponibles dentro del ecosistema Next Studio.",evolution:"El ecosistema",evolutionTitle:"Crece a tu ritmo, sin cambiar de equipo.",contact:"Hablemos",contactTitle:"Construyamos el próximo paso de tu negocio.",contactText:"Cuéntanos qué quieres lograr y te ayudaremos a elegir la solución correcta.",contactCta:"Solicitar información",monthly:"mensual",setup:"Configuración",card:"Tarjeta Digital",language:"English",menu:"Menú" },
  en: { nav:["Home","Solutions","Websites","Apps & Software","AI & Automation","Digital Card","Pricing","About","Contact"],eyebrow:"Digital solutions for Ecuador",title:<>Your business, ready to <span>grow online.</span></>,lead:"Websites, apps, automation, and artificial intelligence built for the companies moving Ecuador forward.",primary:"Explore solutions",secondary:"Request information",solutions:"Solutions",solutionTitle:"A digital presence that works for your business.",plans:"Ecuador pricing",plansTitle:"Start with the solution that fits today.",programs:"Free Programs",programsText:"Explore free tools already available in the Next Studio ecosystem.",evolution:"The ecosystem",evolutionTitle:"Grow at your own pace, with one team.",contact:"Let's talk",contactTitle:"Let's build your business's next step.",contactText:"Tell us what you want to achieve and we'll help you choose the right solution.",contactCta:"Request information",monthly:"monthly",setup:"Setup",card:"Digital Business Card",language:"Español",menu:"Menu" },
};
const anchors = ["home","websites","apps","automation","digital-card","programs","pricing","contact"];

export function EcuadorHome({ locale }: { locale: EcuadorLocale }) { const t=copy[locale]; const localize=(es:string,en:string)=>locale==="es"?es:en; const solutionData: [LucideIcon,string,string][]=[[Globe2,localize("Páginas Web","Websites"),localize("Sitios modernos y claros que generan confianza y convierten visitas en conversaciones.","Modern, clear sites that build trust and turn visits into conversations.")],[CreditCard,localize("Tarjeta Digital","Digital Business Card"),localize("Comparte tu contacto, servicios y enlaces en una tarjeta digital profesional.","Share your contact, services, and links in one polished digital card.")],[Rocket,localize("Apps y Herramientas","Apps & Tools"),localize("Herramientas útiles y aplicaciones a la medida de cómo trabaja tu equipo.","Useful tools and custom apps designed around the way your team works.")],[Bot,"AI & Automation",localize("Automatiza las tareas repetitivas y gana más tiempo para crecer.","Automate repetitive work and give your business more time to grow.")]]; return <><BrandHeader locale={locale} market="ec"/><main className={styles.page}>
  <section id="home" className={styles.hero}><div className={styles.heroCopy}><p className={styles.kicker}>🇪🇨 {t.eyebrow}</p><h1>{t.title}</h1><p>{t.lead}</p><div className={styles.actions}><a className={styles.primary} href="#websites">{t.primary}<ArrowRight size={18}/></a><a className={styles.secondary} href="#contact">{t.secondary}</a></div></div><div className={styles.visual}><div className={styles.orb}/><Image src="/images/ecuador/ecuador-hero.png" alt={localize("Soluciones digitales para un negocio en Ecuador","Digital solutions for an Ecuadorian business")} fill priority sizes="(max-width: 840px) 100vw, 53vw"/></div></section>
  <section id="websites" className={styles.section}><p className={styles.kicker}>{t.solutions}</p><h2>{t.solutionTitle}</h2><div className={styles.solutionGrid}>{solutionData.map(([Icon,title,text],index)=><article id={anchors[index+1]} key={title}><span><Icon size={24}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <PricingShowcase locale={locale} />
  <section id="apps" className={styles.ecosystem}><div><p className={styles.kicker}>{t.evolution}</p><h2>{t.evolutionTitle}</h2><p>{localize("Desde una app gratuita hasta una plataforma a medida: cada solución prepara a tu negocio para la siguiente etapa.","From a free app to a custom platform: every solution prepares your business for the next stage.")}</p></div><ol>{["Free App",t.card,"Website Basic","Business","Business Pro","AI Business","Custom Platform"].map((item,index)=><li key={item}><span>0{index+1}</span>{item}</li>)}</ol></section>
  <section id="programs" className={styles.programs}><div><Sparkles size={24}/><p className={styles.kicker}>{t.programs}</p><h2>{localize("Herramientas útiles para empezar.","Useful tools to get started.")}</h2><p>{t.programsText}</p></div><Link href={`/ec/${locale}/apps`}>{localize("Ver programas","View programs")}<ArrowRight size={17}/></Link></section>
  <section id="contact" className={styles.contact}><p className={styles.kicker}>{t.contact}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><a className={styles.primary} href="#ecuador-lead">{t.contactCta}<ArrowRight size={18}/></a></section><EcuadorLeadForm locale={locale}/></main><BrandFooter locale={locale} market="ec"/></>; }

function PricingShowcase({ locale }: { locale: EcuadorLocale }) {
  const tr = (es: string, en: string) => locale === "es" ? es : en;
  const plans: { icon: LucideIcon; tagline: string; prefix: string; features: string[] }[] = [
    { icon: Globe2, tagline: tr("Presencia profesional para empezar.", "A professional presence to get started."), prefix: tr("Incluye:", "Includes:"), features: [tr("Diseño profesional", "Professional design"), tr("Experiencia responsive", "Responsive experience"), tr("Información y contacto claros", "Clear business and contact information")] },
    { icon: BriefcaseBusiness, tagline: tr("Más herramientas para crecer.", "More tools to grow."), prefix: tr("Todo lo de Basic, más:", "Everything in Basic, plus:"), features: [tr("Diseño pensado para generar consultas", "Design built to generate inquiries"), tr("Presencia de negocio más completa", "A more complete business presence"), tr("Acompañamiento mensual documentado", "Documented monthly service")] },
    { icon: TrendingUp, tagline: tr("Más capacidad para operar y vender.", "More capacity to operate and sell."), prefix: tr("Todo lo de Business, más:", "Everything in Business, plus:"), features: [tr("Experiencia móvil cuidada", "Polished mobile experience"), tr("Base lista para evolucionar", "A foundation ready to evolve"), tr("Preparación para la siguiente etapa digital", "Preparation for the next digital stage")] },
    { icon: Bot, tagline: tr("IA y automatización para escalar.", "AI and automation built to scale."), prefix: tr("Todo lo de Business Pro, más:", "Everything in Business Pro, plus:"), features: [tr("Automatización de seguimientos", "Follow-up automation"), tr("Flujos para leads y clientes", "Lead and client workflows"), tr("Integraciones a medida", "Custom integrations")] },
  ];
  const cardBenefits: [LucideIcon, string][] = [[CircleUserRound, tr("Enlace personalizado", "Custom link")], [QrCode, "QR"], [MessageCircle, "WhatsApp"], [Phone, tr("Llamada", "Call")], [Mail, "Email"], [Save, tr("Guardar contacto", "Save contact")], [Share2, tr("Compartir", "Share")], [Zap, tr("Actualización digital", "Digital updates")]];
  const trust: [LucideIcon, string, string][] = [[MonitorSmartphone, tr("Tecnología profesional", "Professional technology"), tr("Diseño claro para cada pantalla.", "Clear design for every screen.")], [TrendingUp, tr("Soluciones que pueden crecer", "Solutions built to grow"), tr("Una base preparada para evolucionar.", "A foundation ready to evolve.")], [UserRoundCog, tr("Acompañamiento directo", "Direct guidance"), tr("Orientación para elegir el siguiente paso.", "Guidance for choosing the next step.")]];

  return <section id="pricing" className={`${styles.section} ${ps.pricing}`}>
    <div className={ps.heading}><div><p className={styles.kicker}>{tr("Precios Ecuador", "Ecuador pricing")}</p><h2>{tr("Elige el plan ideal para tu negocio.", "Choose the right plan for your business.")}</h2><p>{tr("Soluciones profesionales diseñadas para cada etapa de crecimiento.", "Professional solutions designed for every stage of growth.")}</p></div><div className={ps.promises}><span><MonitorSmartphone size={19}/>{tr("Diseño profesional", "Professional design")}</span><span><UserRoundCog size={19}/>{tr("Acompañamiento directo", "Direct guidance")}</span><span><ShieldCheck size={19}/>{tr("Tecnología confiable", "Reliable technology")}</span></div></div>
    <div className={ps.grid}>{ecuadorMarket.plans.map((plan,index)=>{const detail=plans[index];const Icon=detail.icon;return <article className={index===2?ps.featured:""} key={plan.id}>{index===2&&<b><Sparkles size={13}/>{tr("Más elegido","Most popular")}</b>}<div className={ps.planTitle}><span><Icon size={24}/></span><div><h3>{plan.name}</h3><p>{detail.tagline}</p></div></div><div className={ps.planPrices}><span>{tr("Configuración", "Setup")}<strong>{plan.setup}</strong></span><span>{tr("Mensual", "Monthly")}<strong>{plan.monthly}</strong></span></div><p className={ps.featurePrefix}>{detail.prefix}</p><ul>{detail.features.map(feature=><li key={feature}><Check size={16}/>{feature}</li>)}</ul><a href={`?plan=${encodeURIComponent(plan.name)}#ecuador-lead`}>{tr("Quiero este plan", "Choose this plan")}<ArrowRight size={17}/></a></article>})}</div>
    <div id="digital-card" className={ps.card}><div className={ps.cardMockup}><Image src="/images/digital-card/richard-velez-card-devices-cutout.png" alt={tr("Vista de la Tarjeta Digital", "Digital Business Card preview")} fill sizes="180px"/></div><div className={ps.cardContent}><h3>{tr("Tarjeta Digital", "Digital Business Card")}</h3><p>{tr("Presentación profesional siempre disponible para compartir.", "A professional introduction, always ready to share.")}</p><div className={ps.cardBenefits}>{cardBenefits.map(([Icon,label])=><span key={label}><Icon size={17}/>{label}</span>)}</div></div><div className={ps.cardOffer}><strong>{ecuadorMarket.digitalCard}</strong><span>{tr("Pago único", "One-time payment")}</span><a href="?plan=digital-card#ecuador-lead">{tr("Quiero mi Tarjeta Digital", "I want my Digital Business Card")}<ArrowRight size={17}/></a></div></div>
    <div className={ps.trust}>{trust.map(([Icon,title,text])=><div key={title}><Icon size={24}/><span><strong>{title}</strong><small>{text}</small></span></div>)}</div>
  </section>;
}
