"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import { ArrowRight, Check, Copy, ExternalLink, Globe2, Mail, MessageCircle, Phone, QrCode, Rocket, Share2, Smartphone, UserRound } from "lucide-react";
import { getWhatsAppUrl } from "@/config/social";
import styles from "./DigitalCardLanding.module.css";

type Locale = "es" | "en";
const demo = { es: "https://next-studio-digital-card.vercel.app/es", en: "https://next-studio-digital-card.vercel.app/en" };
const copy = {
  es: {
    nav: ["Inicio", "Beneficios", "Cómo funciona", "Precio"], hero: ["TARJETA DIGITAL NEXT STUDIO", "Tu tarjeta de presentación, ahora digital.", "Comparte tu negocio en segundos. Un QR. Un enlace. Toda tu información.", "VER DEMO", "QUIERO LA MÍA"],
    stepsTitle: "Comparte tus datos en 4 simples pasos", steps: [["Muestra tu QR", "Desde tu propio teléfono."], ["Tu cliente lo escanea", "Sin instalar ninguna aplicación."], ["Abre tu Tarjeta Digital", "Toda tu información aparece al instante."], ["Te contacta", "WhatsApp, teléfono, website y más."]],
    business: "Todo tu negocio en un solo lugar", difference: "La diferencia es clara", traditional: ["Tarjeta Tradicional", "Se acaba", "Se pierde", "La información no se puede actualizar", "No conecta directamente con tu negocio"], digital: ["Tarjeta Digital", "Siempre disponible", "Se comparte al instante", "Puedes actualizar tu información", "Conecta directamente con tu negocio"],
    tryTitle: "Esta es mi Tarjeta Digital", tryLabel: "PRUÉBALA AHORA", tryText: "Escanea el código QR o abre mi tarjeta digital para que veas exactamente lo que recibirás.", view: "VER MI TARJETA DIGITAL", copied: "Enlace copiado", copyLink: "Copiar enlace", price: "PRECIO POR LANZAMIENTO", original: "PRECIO ORIGINAL", oneTime: "Pago único", buy: "QUIERO LA MÍA AHORA", solutions: "¿Quieres conocer más soluciones digitales para tu negocio?", visit: "VISITAR NEXT STUDIO", final: ["Deja de entregar solo tu número.", "Entrega tu negocio completo.", "QUIERO MI TARJETA DIGITAL"],
    floating: "Hola Richard, estoy viendo la landing de la Tarjeta Digital y quiero más información.", purchase: "Hola Richard, vi la Tarjeta Digital de Next Studio y quiero aprovechar el precio de lanzamiento de $70. Quiero información para crear la mía.", language: "Cambiar idioma", all: ["Información de contacto", "WhatsApp y llamada directa", "Email", "Dirección", "Enlaces a redes sociales", "Website de tu negocio", "QR para compartir", "Guardar contacto", "Diseño personalizado", "Funciona en Android y iPhone"]
  },
  en: {
    nav: ["Home", "Benefits", "How it works", "Price"], hero: ["NEXT STUDIO DIGITAL CARD", "Your business card, now digital.", "Share your business in seconds. One QR. One link. All your information.", "SEE DEMO", "GET MINE"],
    stepsTitle: "Share your information in 4 simple steps", steps: [["Show your QR", "From your own phone."], ["Your client scans it", "No app installation required."], ["Opens your Digital Card", "All your information appears instantly."], ["They contact you", "WhatsApp, phone, website and more."]],
    business: "Your entire business in one place", difference: "The difference is clear", traditional: ["Traditional Card", "It runs out", "It gets lost", "Information cannot be updated", "Does not connect directly with your business"], digital: ["Digital Card", "Always available", "Shared instantly", "You can update your information", "Connects directly with your business"],
    tryTitle: "This is my Digital Card", tryLabel: "TRY IT NOW", tryText: "Scan the QR code or open my digital card to see exactly what you'll receive.", view: "VIEW MY DIGITAL CARD", copied: "Link copied", copyLink: "Copy link", price: "LAUNCH PRICE", original: "ORIGINAL PRICE", oneTime: "One-time payment", buy: "GET MINE NOW", solutions: "Want to discover more digital solutions for your business?", visit: "VISIT NEXT STUDIO", final: ["Stop sharing only your phone number.", "Share your entire business.", "GET MY DIGITAL CARD"],
    floating: "Hi Richard, I'm viewing the Digital Card landing page and I'd like more information.", purchase: "Hi Richard, I saw the Next Studio Digital Card and I'd like to take advantage of the $70 launch price. I'd like information about creating mine.", language: "Change language", all: ["Contact information", "WhatsApp and direct calling", "Email", "Address", "Social media links", "Business website", "QR sharing", "Save contact", "Custom design", "Works on Android and iPhone"]
  }
} as const;

export function DigitalCardLanding({ initialLocale }: { initialLocale: Locale }) {
  const [locale, setLocale] = useState<Locale>(initialLocale); const [qr, setQr] = useState(""); const [copied, setCopied] = useState(false); const t = copy[locale];
  useEffect(() => { QRCode.toDataURL(demo[locale], { width: 320, margin: 1, color: { dark: "#08287d", light: "#ffffff" } }).then(setQr); }, [locale]);
  const buy = useMemo(() => getWhatsAppUrl(t.purchase), [t.purchase]); const floating = useMemo(() => getWhatsAppUrl(t.floating), [t.floating]);
  const changeLocale = (next: Locale) => { setLocale(next); window.history.replaceState(null, "", next === "es" ? "/es/tarjeta-digital" : "/en/digital-card"); };
  async function copyLink() { await navigator.clipboard.writeText(demo[locale]); setCopied(true); window.setTimeout(() => setCopied(false), 2000); }
  const stepIcons = [QrCode, Smartphone, UserRound, MessageCircle];
  return <main className={styles.page}>
    <header className={styles.header}><a className={styles.brand} href="#inicio"><Image src="/images/brand/next-studio-logo.png" alt="NEXT STUDIO" width={142} height={92} priority/></a><nav>{t.nav.map((x, i) => <a key={x} href={["#inicio", "#beneficios", "#como-funciona", "#precio"][i]}>{x}</a>)}</nav><div className={styles.headerActions}><div className={styles.languages} aria-label={t.language}><button className={locale === "es" ? styles.activeLang : ""} onClick={() => changeLocale("es")}>🇪🇨 ES</button><button className={locale === "en" ? styles.activeLang : ""} onClick={() => changeLocale("en")}>🇺🇸 EN</button></div><a className={styles.smallCta} href={buy} target="_blank" rel="noreferrer"><Rocket size={16}/>{t.hero[4]}</a></div></header>
    <section id="inicio" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>{t.hero[0]}</p><h1>{t.hero[1]}</h1><p className={styles.lead}>{t.hero[2]}</p><div className={styles.actions}><a href={demo[locale]} target="_blank" rel="noreferrer" className={styles.primary}><QrCode size={20}/>{t.hero[3]}</a><a href={buy} target="_blank" rel="noreferrer" className={styles.secondary}><MessageCircle size={20}/>{t.hero[4]}</a></div><div className={styles.miniBenefits}><span><Phone/>24/7</span><span><Rocket/>{locale === "es" ? "Actualizable" : "Updatable"}</span><span><Share2/>{locale === "es" ? "Fácil de compartir" : "Easy to share"}</span></div></div><div className={styles.heroVisual}><div className={styles.ring}/><div className={styles.phone}><div className={styles.phoneTop}/><Image className={styles.phoneCardAsset} src="/images/digital-card/richard-velez-digital-card-portrait.png" alt="Tarjeta digital original de Richard Vélez" fill priority sizes="(max-width: 800px) 260px, 278px"/></div><aside className={styles.qrCard}><strong>{locale === "es" ? "Escanéame" : "Scan me"}</strong>{qr && <Image src={qr} alt={locale === "es" ? "Código QR de la tarjeta digital" : "Digital card QR code"} width={130} height={130} unoptimized/>}<small>{locale === "es" ? "y guarda mi contacto" : "and save my contact"}</small><b>NS</b></aside></div></section>
    <section id="como-funciona" className={styles.steps}><p className={styles.eyebrow}>{locale === "es" ? "CÓMO FUNCIONA" : "HOW IT WORKS"}</p><h2>{t.stepsTitle}</h2><div>{t.steps.map(([title, desc], i) => { const Icon = stepIcons[i]; return <article key={title}><span><Icon/></span><i>{i + 1}</i><h3>{title}</h3><p>{desc}</p></article>; })}</div></section>
    <section id="beneficios" className={styles.benefits}><article><p className={styles.eyebrow}>{locale === "es" ? "TODO TU NEGOCIO" : "YOUR ENTIRE BUSINESS"}</p><h2>{t.business}</h2><ul>{t.all.map(x => <li key={x}><Check/>{x}</li>)}</ul></article><div className={styles.cardsStack}><Image src="/images/digital-card/richard-velez-card-devices-cutout.png" alt="Tarjetas digitales de Richard Vélez en teléfonos" fill sizes="(max-width: 800px) 100vw, 45vw"/></div></section>
    <section className={styles.compare}><p className={styles.eyebrow}>{locale === "es" ? "DE PAPEL A DIGITAL" : "FROM PAPER TO DIGITAL"}</p><h2>{t.difference}</h2><div><article className={styles.old}><h3>{t.traditional[0]}</h3>{t.traditional.slice(1).map(x => <p key={x}>✕ {x}</p>)}</article><b>VS</b><article className={styles.new}><h3>{t.digital[0]}</h3>{t.digital.slice(1).map(x => <p key={x}>✓ {x}</p>)}</article></div></section>
    <section className={styles.demo}><article className={styles.tryCard}><p className={styles.eyebrow}>{t.tryLabel}</p><h2>{t.tryTitle}</h2><p>{t.tryText}</p><div className={styles.tryActions}><div className={styles.demoQr}>{qr && <Image src={qr} alt="QR" width={138} height={138} unoptimized/>}</div><div><a className={styles.primary} href={demo[locale]} target="_blank" rel="noreferrer"><ExternalLink size={17}/>{t.view}</a><button className={styles.copyButton} onClick={copyLink}><Copy size={17}/>{copied ? t.copied : t.copyLink}</button></div></div></article><article className={styles.priceCard} id="precio"><p className={styles.eyebrow}>{t.price}</p><div><section><small>{t.price}</small><strong>$70</strong></section><section><small>{t.original}</small><s>$130</s></section></div><em>{t.oneTime}</em></article><aside className={styles.buyPanel}><ul>{(locale === "es" ? ["Profesional", "Moderna", "Lista en minutos", "Para cualquier negocio"] : ["Professional", "Modern", "Ready in minutes", "For any business"]).map(x => <li key={x}><Check/>{x}</li>)}</ul><a href={buy} target="_blank" rel="noreferrer" className={styles.buy}><MessageCircle size={20}/>{t.buy}</a></aside></section>
    <section className={styles.secondaryCta}><p>{t.solutions}</p><a href="https://www.nextstudio.agency" target="_blank" rel="noreferrer">{t.visit}<Globe2 size={18}/></a></section>
    <section className={styles.final}><p>{t.final[0]}</p><h2>{t.final[1]}</h2><div><span>✓ {locale === "es" ? "Un QR o un enlace" : "One QR or one link"}</span><span>✓ {locale === "es" ? "Una presentación profesional" : "A professional presentation"}</span><span>✓ {locale === "es" ? "Más conexiones y más clientes" : "More connections and more clients"}</span></div><a href={buy} target="_blank" rel="noreferrer">{t.final[2]} <ArrowRight size={18}/></a></section>
    <a className={styles.floating} href={floating} target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle size={25}/></a>
  </main>;
}
