import Link from "next/link";
import { ArrowRight, Bot, BriefcaseBusiness, Globe2, Sparkles, Workflow, Wrench } from "lucide-react";
import { BrandFooter } from "@/components/design-system/navigation/BrandFooter";
import { BrandHeader } from "@/components/design-system/navigation/BrandHeader";
import type { Market } from "@/lib/market-routing";
import styles from "./AboutPage.module.css";

const copy = {
  es: { hero:"Construimos tecnología para negocios que quieren avanzar.", lead:"En Next Studio combinamos diseño, desarrollo, automatización e inteligencia artificial para transformar necesidades reales de negocio en soluciones digitales prácticas.", solutions:"Ver soluciones", start:"Empezar un proyecto", idea:"La tecnología debe resolver problemas reales.", ideaText:"No se trata solamente de tener una página web. Un negocio puede necesitar conseguir más clientes, organizar contactos, automatizar procesos, mejorar su presencia digital o utilizar IA. Nuestro trabajo es detectar esa necesidad y construir la solución correcta.", build:"Qué construimos", process:"Cómo trabajamos", ai:"Inteligencia artificial con estrategia humana.", aiText:"Usamos IA para acelerar procesos, analizar oportunidades y crear mejores herramientas, siempre al servicio del negocio.", markets:"Dos mercados. Diferentes necesidades. La misma visión: hacer tecnología útil para los negocios.", founder:"Tecnología con mentalidad de negocio.", founderText:"Next Studio nace de la experiencia de trabajar directamente con negocios, marketing, diseño y soluciones digitales. Con la evolución de la inteligencia artificial, esa experiencia se convirtió en una visión más amplia: crear herramientas que permitan a los negocios trabajar de una manera más inteligente.", final:"Tu negocio tiene una próxima etapa. Construyámosla.", finalText:"Cuéntanos qué necesitas mejorar y encontremos la solución adecuada.", talk:"Hablar con Next Studio", diagnosis:"Diagnóstico de Negocio", principles:["Construir con propósito","Mantenerlo práctico","Pensar en crecimiento","Seguir evolucionando"] },
  en: { hero:"We build technology for businesses ready to move forward.", lead:"At Next Studio, we combine design, development, automation and artificial intelligence to turn real business needs into practical digital solutions.", solutions:"Explore Solutions", start:"Start a Project", idea:"Technology should solve real problems.", ideaText:"It is not only about having a website. A business may need more customers, organized contacts, automated processes, a better digital presence, or AI. Our job is to identify that need and build the right solution.", build:"What we build", process:"How we work", ai:"Artificial intelligence with human strategy.", aiText:"We use AI to accelerate processes, analyze opportunities and create better tools, while technology remains in service of the business.", markets:"Two markets. Different needs. The same vision: making technology useful for businesses.", founder:"Technology with a business mindset.", founderText:"Next Studio comes from working directly with businesses, marketing, design and digital solutions. As artificial intelligence evolved, that experience became a broader vision: creating tools that help businesses work more intelligently.", final:"Your business has a next stage. Let’s build it.", finalText:"Tell us what you need to improve and let’s find the right solution.", talk:"Talk to Next Studio", diagnosis:"Business Diagnosis", principles:["Build with purpose","Keep it practical","Think about growth","Keep evolving"] },
} as const;
const services = [["Websites",Globe2],["CRM & Business Systems",BriefcaseBusiness],["Artificial Intelligence",Bot],["Automation",Workflow],["Digital Presence",Sparkles],["Custom Tools",Wrench]] as const;
export function AboutPage({locale,market="us"}:{locale:"es"|"en";market?:Market}){const c=copy[locale]; const base=market==="ec"?`/ec/${locale}`:`/${locale}`; const contact=`${base}/${locale==="es"?"contacto":"contact"}`; const solutions=`${base}/${locale==="es"?"soluciones":"solutions"}`; const diagnosis=locale==="es"?"/es/diagnostico-ia":"/en/ai-business-diagnosis"; return <><BrandHeader locale={locale} market={market}/><main className={styles.page}><section className={styles.hero}><div><p>NEXT STUDIO</p><h1>{c.hero}</h1><span>{c.lead}</span><nav><Link href={solutions}>{c.solutions}<ArrowRight/></Link><Link href={contact}>{c.start}</Link></nav></div><aside><i/><i/><i/><strong>NS</strong></aside></section><section className={styles.section}><h2>{c.idea}</h2><p>{c.ideaText}</p></section><section className={styles.section}><p className={styles.label}>{c.build}</p><div className={styles.cards}>{services.map(([name,Icon])=><article key={name}><Icon/><h3>{name}</h3><p>{locale==="es"?"Soluciones prácticas diseñadas alrededor de tu negocio.":"Practical solutions designed around your business."}</p></article>)}</div></section><section className={styles.process}><p className={styles.label}>{c.process}</p><div>{(locale==="es"?["Entendemos el negocio","Detectamos la necesidad","Diseñamos la solución","Construimos","Conectamos","Mejoramos"]:["We understand the business","We identify the need","We design the solution","We build","We connect","We improve"]).map((step,i)=><span key={step}><b>0{i+1}</b>{step}</span>)}</div></section><section className={styles.ai}><Bot/><div><h2>{c.ai}</h2><p>{c.aiText}</p></div></section><section className={styles.markets}><p>🇺🇸 {locale==="es"?"Estados Unidos":"United States"} &nbsp; · &nbsp; 🇪🇨 Ecuador</p><h2>{c.markets}</h2></section><section className={styles.founder}><p className={styles.label}>{locale==="es"?"DETRÁS DE NEXT STUDIO":"BEHIND NEXT STUDIO"}</p><h2>{c.founder}</h2><p>{c.founderText}</p><strong>Richard Vélez <small>Founder — Next Studio</small></strong></section><section className={styles.principles}>{c.principles.map((p,i)=><span key={p}><b>0{i+1}</b>{p}</span>)}</section><section className={styles.final}><h2>{c.final}</h2><p>{c.finalText}</p><Link href={contact}>{c.talk}<ArrowRight/></Link><Link href={diagnosis}>{c.diagnosis}</Link></section></main><BrandFooter locale={locale} market={market}/></>}
