"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent } from "react";
import { getWhatsAppUrl } from "@/config/social";
import { pricingPlans, type PricingLocale } from "@/content/pricing-v2";
import styles from "./ConversionLanding.module.css";

type Market = "us" | "ec";
type Copy = Record<string, string>;

const copy: Record<PricingLocale, Copy> = {
  es: {
    available:"Agenda abierta para nuevos proyectos", solutions:"Soluciones", process:"Proceso", results:"Resultados", book:"Agendar cita",
    eyebrow:"Tecnología que trabaja para tu negocio", hero:"Tu negocio no necesita más esfuerzo. Necesita un sistema que", converts:"convierta.",
    lead:"Unimos web, automatización, CRM, contenido e inteligencia artificial para atraer clientes, dar seguimiento y vender más—sin complicarte.", diagnose:"Descubre qué está frenando tu negocio", whatsapp:"Hablar por WhatsApp", meeting:"¿Prefieres hablar directamente? Agenda una reunión", meetingSub:"Elige tu día y hora en Google Calendar · Google Meet", bilingual:"Servicio bilingüe", support:"Soporte cercano", grow:"Hecho para crecer", connected:"Todo tu crecimiento, conectado.", automation:"Automatización activa", working:"Trabajando 24/7", ecosystem:"ECOSISTEMA DIGITAL NEXT STUDIO", engines:"Cinco motores. Una sola dirección: crecer.", authority:"AUTORIDAD DIGITAL", future:"No hablamos del futuro.", building:"Ya lo estamos construyendo.", authorityText:"Next Studio desarrolla herramientas propias para que los negocios locales compitan con tecnología que antes solo estaba al alcance de grandes empresas.", operational:"Sistemas en operación", diagnosisProduct:"Diagnóstico de Negocio", diagnosisProductSub:"Detecta oportunidades con IA", crmSub:"Organiza y activa seguimientos", contentSub:"Contenido con dirección comercial", platformSub:"Documentos, ventas y análisis",
    problem:"EL PROBLEMA REAL", presence:"Tener presencia digital no basta.", produce:"Debe producir resultados.", problemText:"Muchos negocios tienen redes, una web o publicidad, pero todo está desconectado. Nosotros convertimos piezas sueltas en un sistema comercial.",
    method:"EL MÉTODO NEXT", methodTitle:"De improvisar cada día a tener un negocio", direction:"con dirección.", methodText:"No empezamos vendiéndote una herramienta. Empezamos entendiendo dónde estás perdiendo oportunidades y construimos desde ahí.", startDiagnosis:"Empezar mi diagnóstico", google:"POSICIONAMIENTO EN GOOGLE", googleTitle:"Una página web debe existir.", appear:"Y también debe aparecer.", googleText:"Construimos tu presencia para que Google entienda qué haces, dónde trabajas y por qué debe mostrarte a clientes cercanos.", near:"mejor negocio cerca de mí", localPosition:"POSICIÓN LOCAL", found:"Tu negocio aparece cuando te necesitan", visibility:"Visibilidad digital", analyze:"Analizar mi visibilidad", searchReady:"Web preparada para búsquedas", seo:"SEO local básico",
    real:"PARA NEGOCIOS REALES", technology:"Tecnología poderosa.", human:"Explicada de forma humana.", commitment:"NUESTRO COMPROMISO", quote:"No te entregamos tecnología y desaparecemos. Te ayudamos a entenderla, usarla y convertirla en crecimiento.", clear:"Claro", clearSub:"Sin palabras complicadas", strategic:"Estratégico", strategicSub:"Cada acción tiene un propósito", personal:"Cercano", personalSub:"Acompañamiento real", next:"TU PRÓXIMO PASO", nextTitle:"Descubre en minutos qué está frenando el crecimiento de tu negocio.", nextText:"Recibe claridad sobre tu presencia digital, ventas, seguimiento y automatización. Sin compromiso y sin lenguaje complicado.", personalized:"Resultado personalizado", priorities:"Oportunidades prioritarias", stepsClear:"Próximos pasos claros", tell:"Cuéntanos de tu negocio", name:"Nombre", business:"Negocio", need:"¿Qué necesitas mejorar?", namePh:"Tu nombre", businessPh:"Nombre del negocio", receive:"Recibir mi diagnóstico", reply:"Te responderemos personalmente por WhatsApp.", footerTag:"Automatiza. Organiza. Crece.", connect:"Conecta", markets:"Mercados", footerLine:"El futuro de tu negocio comienza con una decisión.", talk:"Hablemos"
  },
  en: {
    available:"Now booking new projects", solutions:"Solutions", process:"Process", results:"Results", book:"Book a call",
    eyebrow:"Technology that works for your business", hero:"Your business doesn't need more effort. It needs a system that", converts:"converts.",
    lead:"We combine web, automation, CRM, content and AI to attract leads, follow up and sell more—without the complexity.", diagnose:"Find what's holding your business back", whatsapp:"Chat on WhatsApp", meeting:"Prefer to talk directly? Book a meeting", meetingSub:"Choose your date and time in Google Calendar · Google Meet", bilingual:"Bilingual service", support:"Personal support", grow:"Built to grow", connected:"Your entire growth, connected.", automation:"Automation active", working:"Working 24/7", ecosystem:"NEXT STUDIO DIGITAL ECOSYSTEM", engines:"Five engines. One direction: growth.", authority:"DIGITAL AUTHORITY", future:"We don't just talk about the future.", building:"We're already building it.", authorityText:"Next Studio builds proprietary tools so local businesses can compete with technology once available only to large companies.", operational:"Systems operational", diagnosisProduct:"Business Diagnosis", diagnosisProductSub:"Finds opportunities with AI", crmSub:"Organizes and activates follow-ups", contentSub:"Content with sales direction", platformSub:"Documents, sales and analytics",
    problem:"THE REAL PROBLEM", presence:"A digital presence isn't enough.", produce:"It must produce results.", problemText:"Many businesses have social media, a website or ads, but nothing connects. We turn scattered pieces into one sales system.",
    method:"THE NEXT METHOD", methodTitle:"From improvising every day to a business", direction:"with direction.", methodText:"We don't begin by selling you a tool. We begin by finding where you're losing opportunities and build from there.", startDiagnosis:"Start my diagnosis", google:"GOOGLE POSITIONING", googleTitle:"A website must exist.", appear:"And it must be found.", googleText:"We build your presence so Google understands what you do, where you work and why it should show you to nearby customers.", near:"best business near me", localPosition:"LOCAL POSITION", found:"Your business appears when customers need it", visibility:"Digital visibility", analyze:"Analyze my visibility", searchReady:"Search-ready website", seo:"Basic local SEO",
    real:"FOR REAL BUSINESSES", technology:"Powerful technology.", human:"Explained like a human.", commitment:"OUR COMMITMENT", quote:"We don't hand you technology and disappear. We help you understand it, use it and turn it into growth.", clear:"Clear", clearSub:"No confusing jargon", strategic:"Strategic", strategicSub:"Every action has a purpose", personal:"Personal", personalSub:"Real human support", next:"YOUR NEXT STEP", nextTitle:"Discover in minutes what's slowing down your business growth.", nextText:"Get clarity on your digital presence, sales, follow-up and automation. No commitment and no confusing jargon.", personalized:"Personalized result", priorities:"Priority opportunities", stepsClear:"Clear next steps", tell:"Tell us about your business", name:"Name", business:"Business", need:"What do you need to improve?", namePh:"Your name", businessPh:"Business name", receive:"Get my diagnosis", reply:"We'll personally reply on WhatsApp.", footerTag:"Automate. Organize. Grow.", connect:"Connect", markets:"Markets", footerLine:"Your business future begins with one decision.", talk:"Let's talk"
  }
};

const solutions = {
  es:[
    ["Webs que convierten","No una página bonita: una experiencia diseñada para generar confianza, conversaciones y ventas.",["Mensaje estratégico","Diseño premium bilingüe","CTA y seguimiento"],"service-websites.png"],
    ["CRM y automatización","Cada contacto organizado, cada oportunidad visible y cada seguimiento en el momento correcto.",["Pipeline de ventas","Recordatorios automáticos","Control del negocio"],"service-crm.png"],
    ["IA aplicada al negocio","Herramientas que ahorran tiempo, crean contenido y ayudan a tomar mejores decisiones.",["Diagnóstico inteligente","Contenido estratégico","Procesos más rápidos"],"service-ai.png"],
    ["Visibilidad y crecimiento","Posicionamiento local, Google y contenido para que te encuentren, te entiendan y te elijan.",["Google Business","Contenido para redes","Reputación digital"],"service-google.png"]
  ],
  en:[
    ["Websites that convert","Not just a pretty page: an experience designed to build trust, conversations and sales.",["Strategic message","Premium bilingual design","CTA and follow-up"],"service-websites.png"],
    ["CRM & automation","Every lead organized, every opportunity visible and every follow-up right on time.",["Sales pipeline","Automatic reminders","Business control"],"service-crm.png"],
    ["AI for your business","Tools that save time, create content and help you make better decisions.",["Smart diagnosis","Strategic content","Faster processes"],"service-ai.png"],
    ["Visibility & growth","Local positioning, Google and content so customers find, understand and choose you.",["Google Business","Social content","Digital reputation"],"service-google.png"]
  ]
} as const;

const steps = {
  es:[["Diagnosticamos","Revisamos presencia, ventas, seguimiento y oportunidades."],["Diseñamos la ruta","Priorizamos lo que puede generar mayor impacto primero."],["Construimos","Conectamos las herramientas sin complicar tu operación."],["Medimos y mejoramos","Tu sistema evoluciona con datos reales y tus objetivos."]],
  en:[["We diagnose","We assess visibility, sales, follow-up and opportunities."],["We design the roadmap","We prioritize what can create the greatest impact first."],["We build","We connect the tools without complicating your operation."],["We measure & improve","Your system evolves with real data and your goals."]]
} as const;

const needs = {es:["Conseguir más clientes","Crear o mejorar mi web","Organizar ventas con CRM","Automatizar con IA","No estoy seguro todavía"],en:["Get more customers","Create or improve my website","Organize sales with CRM","Automate with AI","I'm not sure yet"]};
const calendar="https://calendar.app.google/rVAAWr9ECSrbN6yx9";

export function ConversionLanding({locale,market="us"}:{locale:PricingLocale;market?:Market}) {
  const c=copy[locale];
  const home=market==="ec"?`/ec/${locale}`:`/${locale}`;
  const language=market==="ec"?(locale==="es"?"/ec/en/pricing":"/ec/es/precios"):(locale==="es"?"/en/pricing":"/es/precios");
  const marketRoute=market==="ec"?(locale==="es"?"/es/precios":"/en/pricing"):(locale==="es"?"/ec/es/precios":"/ec/en/pricing");
  const chat=getWhatsAppUrl(locale==="es"?"Hola Next Studio, quiero mejorar mi negocio":"Hi Next Studio, I want to improve my business");
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const intro=locale==="es"?"Hola Next Studio, quiero mi diagnóstico.":"Hi Next Studio, I want my free diagnosis.";const message=`${intro}\n\n${c.name}: ${form.get("name")}\n${c.business}: ${form.get("business")}\n${c.need}: ${form.get("need")}`;window.open(getWhatsAppUrl(message),"_blank","noopener,noreferrer")}
  return <div className={styles.page}>
    <div className={styles.topbar}><i/><span>{c.available}</span></div>
    <header className={`${styles.nav} ${styles.shell}`}><Link className={styles.logo} href={home}><Image src="/images/conversion-landing/next-studio-logo.png" alt="Next Studio — Building Digital Businesses" width={190} height={58} priority/></Link><nav><a href="#solutions">{c.solutions}</a><a href="#process">{c.process}</a><a href="#results">{c.results}</a></nav><div className={styles.navActions}><Link className={styles.pill} href={language}>{locale==="es"?"EN":"ES"}</Link><Link className={styles.pill} href={marketRoute}>{market==="us"?"EC":"USA"}</Link><a className={styles.calendar} href={calendar} target="_blank" rel="noreferrer">▣ <span>{c.book}</span></a></div></header>
    <main id="top">
      <section className={`${styles.hero} ${styles.shell}`}><div><span className={styles.eyebrow}>✦ {c.eyebrow}</span><h1>{c.hero} <em>{c.converts}</em></h1><p className={styles.lead}>{c.lead}</p><div className={styles.heroActions}><a className={styles.button} href="#diagnosis">{c.diagnose} →</a><a className={styles.textLink} href={chat} target="_blank" rel="noreferrer">{c.whatsapp} ↗</a></div><a className={styles.bookInline} href={calendar} target="_blank" rel="noreferrer"><b>▣</b><span><strong>{c.meeting}</strong><small>{c.meetingSub}</small></span><i>→</i></a><div className={styles.trust}><div><b>ES / EN</b><small>{c.bilingual}</small></div><div><b>USA + EC</b><small>{c.support}</small></div><div><b>100%</b><small>{c.grow}</small></div></div></div><div className={styles.heroVisual}><Image src="/images/conversion-landing/next-studio-tech-hero.png" alt="Next Studio technology ecosystem" fill priority sizes="(max-width:900px) 92vw, 46vw"/><div className={styles.shade}/><div className={styles.imageProof}><small>● NEXT STUDIO OS</small><b>{c.connected}</b><div><span>AI</span><span>CRM</span><span>WEB</span><span>GOOGLE</span></div></div><div className={styles.float}>⚡ <span><b>{c.automation}</b><small>{c.working}</small></span></div></div></section>
      <section className={styles.proof}><div className={`${styles.shell} ${styles.proofInner}`}><div><small>{c.ecosystem}</small><strong>{c.engines}</strong></div><aside>{["WEBSITE","CRM","AI","CONTENT","GOOGLE"].map(x=><span key={x}><i/>{x}</span>)}</aside></div></section>
      <section className={`${styles.authority} ${styles.shell}`}><div><span className={styles.kicker}>{c.authority}</span><h2>{c.future}<br/><em>{c.building}</em></h2><p>{c.authorityText}</p></div><div className={styles.console}><header><span>● NEXT STUDIO ECOSYSTEM</span><small>{c.operational}</small></header><div>{[["AI",c.diagnosisProduct,c.diagnosisProductSub],["CRM","Sales Intelligence",c.crmSub],["AI","Content Strategy",c.contentSub],["PRO","Business Platform",c.platformSub]].map(x=><article key={x[1]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span><i>→</i></article>)}</div></div></section>
      <section className={`${styles.section} ${styles.shell}`} id="solutions"><div className={styles.heading}><span className={styles.kicker}>{c.problem}</span><h2>{c.presence}<br/><em>{c.produce}</em></h2><p>{c.problemText}</p></div><div className={styles.solutionGrid}>{solutions[locale].map((x,i)=><article className={styles.solution} key={x[0]}><figure><Image src={`/images/conversion-landing/${x[3]}`} alt={x[0]} fill sizes="(max-width:620px) 92vw, 45vw"/><span>0{i+1}</span></figure><h3>{x[0]}</h3><p>{x[1]}</p><ul>{x[2].map(y=><li key={y}>{y}</li>)}</ul></article>)}</div></section>
      <Pricing locale={locale}/>
      <section className={styles.method} id="process"><div className={`${styles.shell} ${styles.methodGrid}`}><div><span className={styles.kicker}>{c.method}</span><h2>{c.methodTitle} <em>{c.direction}</em></h2><p>{c.methodText}</p><a className={`${styles.button} ${styles.ghost}`} href="#diagnosis">{c.startDiagnosis} →</a></div><div className={styles.steps}>{steps[locale].map((x,i)=><article key={x[0]}><b>0{i+1}</b><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></div></section>
      <section className={styles.google}><div className={`${styles.shell} ${styles.googleGrid}`}><div className={styles.googleVisual}><Image src="/images/conversion-landing/service-google.png" alt="Local business visible in Google search" fill sizes="(max-width:900px) 92vw,46vw"/><div className={styles.search}><div><b>G</b><strong>{c.near}</strong><i>⌕</i></div><article><b>01</b><span><small>{c.localPosition}</small><strong>{c.found}</strong></span><i>↗</i></article><footer><span>{c.visibility}</span><b>92%</b><i><u/></i></footer></div></div><div><span className={styles.kicker}>{c.google}</span><h2>{c.googleTitle}<br/><em>{c.appear}</em></h2><p>{c.googleText}</p><div className={styles.googleBenefits}><span><b>01</b><small>{c.searchReady}</small></span><span><b>02</b><small>Google Business</small></span><span><b>03</b><small>{c.seo}</small></span></div><a className={styles.button} href="#diagnosis">{c.analyze} →</a></div></div></section>
      <section className={`${styles.section} ${styles.shell}`} id="results"><div className={`${styles.heading} ${styles.center}`}><span className={styles.kicker}>{c.real}</span><h2>{c.technology}<br/><em>{c.human}</em></h2></div><div className={styles.industries}>{["RESTAURANTS","BEAUTY & SPA","CONSTRUCTION","PRINTING","BARBERSHOPS","LOCAL SERVICES"].map(x=><span key={x}>{x}</span>)}</div><div className={styles.commitment}><div><span className={styles.kicker}>{c.commitment}</span><blockquote>{c.quote}</blockquote><div className={styles.founder}><b>RV</b><span><strong>Richard Vélez</strong><small>Founder, Next Studio</small></span></div></div><aside>{[[c.clear,c.clearSub],[c.strategic,c.strategicSub],[c.personal,c.personalSub]].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</aside></div></section>
      <section className={styles.diagnosis} id="diagnosis"><div className={`${styles.shell} ${styles.diagnosisGrid}`}><div><span className={styles.light}>✦ {c.next}</span><h2>{c.nextTitle}</h2><p>{c.nextText}</p><div className={styles.points}><span>✓ {c.personalized}</span><span>✓ {c.priorities}</span><span>✓ {c.stepsClear}</span></div></div><form onSubmit={submit}><header><span>01 / 01</span><b>{c.tell}</b></header><label>{c.name}<input name="name" required placeholder={c.namePh}/></label><label>{c.business}<input name="business" required placeholder={c.businessPh}/></label><label>{c.need}<select name="need">{needs[locale].map(x=><option key={x}>{x}</option>)}</select></label><button className={styles.button}>{c.receive} →</button><small>{c.reply}</small></form></div></section>
    </main>
    <footer className={styles.footer}><div className={styles.signal}><i/> NEXT STUDIO DIGITAL INFRASTRUCTURE <b>ONLINE</b></div><div className={`${styles.shell} ${styles.footerGrid}`}><div><Link href={home}><Image src="/images/conversion-landing/next-studio-logo.png" alt="Next Studio" width={230} height={85}/></Link><p>{c.footerTag}</p></div><div><b>{c.connect}</b><a href="https://www.nextstudio.agency">nextstudio.agency</a><a href={getWhatsAppUrl()}>+1 239 333 7935</a></div><div><b>{c.markets}</b><span>New York · USA</span><span>Ecuador</span></div></div><div className={`${styles.shell} ${styles.copyright}`}><span>© 2026 Next Studio</span><span>{c.footerLine}</span></div></footer>
  </div>
}

function Pricing({locale}:{locale:PricingLocale}){const es=locale==="es";return <section className={styles.pricing} id="plans"><div className={styles.shell}><header className={`${styles.heading} ${styles.center}`}><span className={styles.kicker}>{es?"PLANES NEXT STUDIO":"NEXT STUDIO PLANS"}</span><h2>{es?"Comienza sin pagar cientos de dólares.":"Start without paying hundreds upfront."}</h2><p>{es?"Tu página profesional, tecnología y acompañamiento por una mensualidad sencilla. Sin pago inicial.":"Your professional website, technology and support for one simple monthly payment. No upfront fee."}</p></header><div className={styles.pricingGrid}>{pricingPlans.map((p,i)=><article className={`${styles.priceCard} ${i===1?styles.recommended:""}`} key={p.planId}><span>{i===0?(es?"PARA COMENZAR":"GET STARTED"):i===1?(es?"RECOMENDADO":"RECOMMENDED"):(es?"MÁS TECNOLOGÍA":"MORE TECHNOLOGY")}</span><h3>{p.name}</h3><p>{es?["Presencia profesional para comenzar","Atrae clientes y recibe citas","Organiza, automatiza y crece"][i]:["A professional presence to get started","Attract customers and book appointments","Organize, automate and grow"][i]}</p><div><b>${p.price}</b><small>{es?"/mes":"/month"}</small></div><strong>{es?"Setup gratis":"Free setup"}</strong><ul>{p.features[locale].map(x=><li key={x}>✓ {x}</li>)}</ul><Link className={styles.button} href={`/pay/${p.slug}`}>{es?"Elegir":"Choose"} {p.name} →</Link></article>)}</div><p className={styles.priceNote}>{es?"Todos los planes requieren un compromiso mínimo de 12 meses. Servicios adicionales se cotizan por separado.":"All plans require a minimum 12-month commitment. Additional services are quoted separately."}</p></div></section>}
