import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Bot, ChartNoAxesCombined, CircleGauge, Globe2, MessageSquareText, SearchCheck, Sparkles, Workflow } from "lucide-react";
import type { Locale } from "@/types/locale";
import styles from "./AIDiagnosisSpotlight.module.css";

const content = {
  es: { title: "¿Qué está frenando el crecimiento de tu negocio?", text: "Obtén un diagnóstico digital avanzado de tu negocio con Inteligencia Artificial y descubre dónde estás perdiendo oportunidades.", areas: ["Website", "Google", "Reviews", "Redes Sociales", "Ventas", "Leads", "CRM", "Automatización", "Inteligencia Artificial"], scores: [["Presencia Digital",82,"good"],["Conversión",61,"warning"],["Automatización",34,"critical"],["Marketing",58,"warning"]], cta: "DIAGNOSTICAR MI NEGOCIO GRATIS", note: "Gratis · 3–5 minutos · Resultado inmediato · Español / English" },
  en: { title: "What is holding back your business growth?", text: "Get an advanced AI-powered digital diagnosis of your business and discover where opportunities are being lost.", areas: ["Website", "Google", "Reviews", "Social Media", "Sales", "Leads", "CRM", "Automation", "Artificial Intelligence"], scores: [["Digital Presence",82,"good"],["Conversion",61,"warning"],["Automation",34,"critical"],["Marketing",58,"warning"]], cta: "DIAGNOSE MY BUSINESS FREE", note: "Free · 3–5 minutes · Instant results · Español / English" },
} as const;
const icons = [Globe2,SearchCheck,MessageSquareText,ChartNoAxesCombined,CircleGauge,Sparkles,Bot,Workflow,Bot];

export function AIDiagnosisSpotlight({locale}:{locale:Locale}){const c=content[locale];const href=locale==="es"?"/es/diagnostico-ia":"/en/ai-business-diagnosis";const metricIcons=[Globe2,CircleGauge,Workflow,ChartNoAxesCombined];const stateLabel=(state:string)=>state==="good"?(locale==="es"?"ÓPTIMO":"GOOD"):state==="warning"?(locale==="es"?"ATENCIÓN":"ATTENTION"):(locale==="es"?"CRÍTICO":"CRITICAL");return <section className={styles.section} aria-labelledby="diagnosis-title"><div className={styles.glow}/><div className={styles.container}><div className={styles.copy}><p className={styles.eyebrow}><Sparkles size={15}/>NS AI BUSINESS DIAGNOSIS™</p><h2 id="diagnosis-title">{c.title}</h2><p className={styles.lead}>{c.text}</p><div className={styles.areas}>{c.areas.map((area,index)=>{const Icon=icons[index];return <span key={area}><Icon size={16}/>{area}</span>})}</div><Link href={href} className={styles.cta}>{c.cta}<ArrowRight size={19}/></Link><small>{c.note}</small></div><div className={styles.scoreCard}><div className={styles.techGrid}/><div className={styles.brandPlate}><Image src="/images/brand/next-studio-logo-official.png" alt="Next Studio" width={138} height={92}/><span>AI BUSINESS INTELLIGENCE</span><i/></div><div className={styles.scannerStage}><div className={styles.orbitDots}/><div className={styles.scanner}><div className={styles.scannerTicks}/><div className={styles.scoreCore}><strong>67</strong><span>/100</span><small>DIGITAL HEALTH SCORE</small></div></div><div className={styles.aiActive}><i/><Bot size={14}/>{locale==="es"?"ANÁLISIS IA ACTIVO":"AI ANALYSIS ACTIVE"}</div></div><div className={styles.techChips}>{["Website","Google","Reviews","CRM","Leads",locale==="es"?"Automatización":"Automation"].map(item=><span key={item}>{item}</span>)}</div><div className={styles.metricGrid}>{c.scores.map(([label,value,state],index)=>{const Icon=metricIcons[index];return <article key={label}><div className={styles.metricIcon}><Icon size={17}/></div><div><p>{label}</p><small className={styles[state]}>{stateLabel(state)}</small></div><strong>{value}</strong><span className={styles[state]}/></article>})}</div><div className={styles.dataLine}><span>NS AI</span><i/><small>{locale==="es"?"ESCANEO DIGITAL COMPLETO":"DIGITAL SCAN COMPLETE"}</small></div></div></div></section>}
