"use client";

import { FormEvent, useState } from "react";
import { CheckCircle2, Mail, MessageCircle } from "lucide-react";
import { BrandHeader } from "@/components/design-system/navigation/BrandHeader";
import { BrandFooter } from "@/components/design-system/navigation/BrandFooter";
import s from "./ContactPage.module.css";

const businessEmail = "info@nextprintnyc.com";
const whatsapp = "12393337935";

const copy = {
  en: { eyebrow: "START A PROJECT", title: "Tell us what you want to build.", intro: "Use this form for a complete project request or quote. For a quick question, message us on WhatsApp.", form: "Project request", immediate: "Need an immediate answer?", talk: "Talk to us on WhatsApp", email: "Email", submit: "Send project request", successTitle: "Your project request is ready to send.", success: "Your email app has opened with your project details. Send it to deliver your request, or continue the conversation on WhatsApp.", continue: "Continue on WhatsApp", fields: ["Full Name", "Business Name", "Email", "Phone / WhatsApp", "Country", "Service Needed", "Industry", "Estimated Budget", "Project Description", "Preferred Contact Method", "Preferred Language"], select: ["Select a service", "Website", "Custom Business Platform", "CRM System", "E-commerce", "Business Tools", "Other"], industry: ["Select an industry", "Printing", "Construction", "Restaurants", "Beauty", "Professional Services", "Clothing Brands", "Medical", "Real Estate", "Other"], budget: ["Select a budget", "Under $1,000", "$1,000 – $3,000", "$3,000 – $7,000", "$7,000+", "Let’s discuss"], contact: ["Email", "WhatsApp", "Phone"], language: ["English", "Spanish", "Both"] },
  es: { eyebrow: "INICIA UN PROYECTO", title: "Cuéntanos qué deseas crear.", intro: "Usa este formulario para una solicitud completa o una cotización. Para una pregunta rápida, escríbenos por WhatsApp.", form: "Solicitud de proyecto", immediate: "¿Necesitas una respuesta inmediata?", talk: "Hablar por WhatsApp", email: "Correo electrónico", submit: "Enviar solicitud de proyecto", successTitle: "Tu solicitud de proyecto está lista para enviar.", success: "Tu aplicación de correo se abrió con los detalles del proyecto. Envía el correo para entregar tu solicitud o continúa la conversación por WhatsApp.", continue: "Continuar por WhatsApp", fields: ["Nombre completo", "Nombre del negocio", "Email", "Teléfono / WhatsApp", "País", "Servicio que necesitas", "Industria", "Presupuesto estimado", "Descripción del proyecto", "Método de contacto preferido", "Idioma preferido"], select: ["Selecciona un servicio", "Página web", "Plataforma personalizada", "Sistema CRM", "E-commerce", "Herramientas de negocio", "Otro"], industry: ["Selecciona una industria", "Imprentas", "Construcción", "Restaurantes", "Belleza", "Servicios profesionales", "Marcas de ropa", "Servicios médicos", "Bienes raíces", "Otra"], budget: ["Selecciona un presupuesto", "Menos de $1,000", "$1,000 – $3,000", "$3,000 – $7,000", "$7,000+", "Hablemos"], contact: ["Email", "WhatsApp", "Teléfono"], language: ["Inglés", "Español", "Ambos"] },
} as const;

export function ContactPage({ locale }: { locale: "en" | "es" }) {
  const c = copy[locale]; const [sent, setSent] = useState(false);
  const onSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const body = Array.from(data.entries()).map(([key, value]) => `${key}: ${value}`).join("\n"); const subject = locale === "en" ? "New NEXT STUDIO project request" : "Nueva solicitud de proyecto de NEXT STUDIO"; setSent(true); window.location.href = `mailto:${businessEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; };
  const chat = locale === "en" ? "Hello, I would like immediate help with my project." : "Hola, deseo ayuda inmediata con mi proyecto.";
  return <><BrandHeader locale={locale}/><main className={s.page}><section className={s.hero}><p>{c.eyebrow}</p><h1>{c.title}</h1><span>{c.intro}</span></section><section className={s.content}><div className={s.contactInfo}><div><MessageCircle size={24}/><p>{c.immediate}</p><a className={s.whatsapp} target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(chat)}`}>{c.talk}</a></div><div><Mail size={24}/><p>{c.email}</p><a href={`mailto:${businessEmail}`}>{businessEmail}</a></div></div><form className={s.form} onSubmit={onSubmit}><h2>{c.form}</h2><div className={s.grid}><Field label={c.fields[0]} name="Full Name" required/><Field label={c.fields[1]} name="Business Name" required/><Field label={c.fields[2]} name="Email" type="email" required/><Field label={c.fields[3]} name="Phone / WhatsApp" required/><Field label={c.fields[4]} name="Country" required/><Select label={c.fields[5]} name="Service Needed" values={c.select}/><Select label={c.fields[6]} name="Industry" values={c.industry}/><Select label={c.fields[7]} name="Estimated Budget" values={c.budget}/><Select label={c.fields[9]} name="Preferred Contact Method" values={c.contact}/><Select label={c.fields[10]} name="Preferred Language" values={c.language}/></div><label className={s.full}>{c.fields[8]}<textarea name="Project Description" required rows={6}/></label><button className={s.submit} type="submit">{c.submit}</button>{sent && <div className={s.success}><CheckCircle2 size={24}/><div><strong>{c.successTitle}</strong><p>{c.success}</p><a target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(chat)}`}>{c.continue}</a></div></div>}</form></section></main><BrandFooter locale={locale}/></>;
}
function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label>{label}<input {...props}/></label>; }
function Select({ label, values, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; values: readonly string[] }) { return <label>{label}<select {...props}>{values.map((value, index) => <option key={value} value={index === 0 ? "" : value} disabled={index === 0}>{value}</option>)}</select></label>; }
