import type{Locale}from"@/types/locale";
type Detail={title:string;subtitle:string;description:string;features:string[];ideal:string[];cta:string;visual:string};
export const platformDetails:Record<Locale,Detail[]>={en:[
{title:"CRM Systems",subtitle:"Manage customers, communication and sales in one place.",description:"A centralized system that helps your business organize contacts, track conversations, follow opportunities and maintain stronger customer relationships.",features:["Customer profiles","Contact history","Lead tracking","Sales pipeline","Follow-up reminders","Notes and internal tasks","Reports and analytics","Email integration"],ideal:["Service businesses","Print shops","Contractors","Consultants","Sales teams","Local businesses"],cta:"Build My CRM",visual:"crm-system.png"},
{title:"Order Management",subtitle:"Control every order from request to delivery.",description:"A complete platform to receive, organize and track customer orders while keeping your team updated throughout the entire production process.",features:["Order creation","Status tracking","Customer records","Product details","Production stages","Payment tracking","Delivery information","Automated notifications"],ideal:["Print shops","Clothing businesses","Restaurants","Retail stores","Manufacturers","Custom product companies"],cta:"Organize My Orders",visual:"order-management.png"},
{title:"Client Portals",subtitle:"Give your customers secure access to their projects.",description:"A private client experience where customers can review updates, approve work, download documents, make payments and communicate with your business.",features:["Secure access links","Project status","File downloads","Design approvals","Online payments","Messages","Invoices and estimates","Activity history"],ideal:["Creative agencies","Print shops","Contractors","Consultants","Professional services","Custom project businesses"],cta:"Create My Client Portal",visual:"workflow-platform.png"},
{title:"Document Workflows",subtitle:"Create, send, approve and track business documents.",description:"Automate the creation and management of estimates, invoices, proposals, contracts and approval documents from one simple platform.",features:["Estimates","Invoices","Proposals","Contracts","Electronic signatures","Approval tracking","PDF generation","Shareable public links"],ideal:["Service companies","Contractors","Consultants","Agencies","Print shops","Sales teams"],cta:"Automate My Documents",visual:"workflow-platform.png"},
{title:"Booking Platforms",subtitle:"Let customers schedule and pay online at any time.",description:"A professional booking system that manages availability, appointments, reminders, customer information and online payments.",features:["Online scheduling","Calendar management","Service selection","Staff availability","Automated reminders","Customer profiles","Online payments","Cancellation rules"],ideal:["Beauty salons","Medical offices","Coaches","Therapists","Consultants","Home service businesses"],cta:"Create My Booking System",visual:"order-management.png"},
{title:"Custom Business Systems",subtitle:"Software designed around the way your company operates.",description:"We build custom platforms that connect your processes, customers, team and data into one powerful business system.",features:["Custom dashboards","User roles","Workflow automation","Reports and analytics","CRM integration","Payment integration","Internal tools","AI-powered features"],ideal:["Growing companies","Multi-service businesses","Print companies","Construction companies","E-commerce operations","Businesses with unique workflows"],cta:"Build My Custom System",visual:"crm-system.png"}],
es:[
{title:"Sistemas CRM",subtitle:"Administra clientes, comunicación y ventas desde un solo lugar.",description:"Un sistema centralizado que ayuda a tu empresa a organizar contactos, registrar conversaciones, dar seguimiento a oportunidades y fortalecer la relación con tus clientes.",features:["Perfiles de clientes","Historial de contactos","Seguimiento de prospectos","Embudo de ventas","Recordatorios de seguimiento","Notas y tareas internas","Reportes y analíticas","Integración con correo electrónico"],ideal:["Empresas de servicios","Imprentas","Contratistas","Consultores","Equipos de ventas","Negocios locales"],cta:"Crear mi CRM",visual:"crm-system.png"},
{title:"Gestión de pedidos",subtitle:"Controla cada pedido desde la solicitud hasta la entrega.",description:"Una plataforma completa para recibir, organizar y dar seguimiento a los pedidos de tus clientes, manteniendo a tu equipo informado durante todo el proceso de producción.",features:["Creación de pedidos","Seguimiento de estados","Registro de clientes","Detalles de productos","Etapas de producción","Control de pagos","Información de entrega","Notificaciones automáticas"],ideal:["Imprentas","Negocios de ropa","Restaurantes","Tiendas","Fabricantes","Empresas de productos personalizados"],cta:"Organizar mis pedidos",visual:"order-management.png"},
{title:"Portales para clientes",subtitle:"Brinda a tus clientes acceso seguro a sus proyectos.",description:"Una experiencia privada donde los clientes pueden revisar avances, aprobar trabajos, descargar documentos, realizar pagos y comunicarse con tu empresa.",features:["Enlaces de acceso seguro","Estado del proyecto","Descarga de archivos","Aprobación de diseños","Pagos online","Mensajes","Facturas y estimados","Historial de actividad"],ideal:["Agencias creativas","Imprentas","Contratistas","Consultores","Servicios profesionales","Negocios de proyectos personalizados"],cta:"Crear mi portal de clientes",visual:"workflow-platform.png"},
{title:"Flujos de documentos",subtitle:"Crea, envía, aprueba y controla documentos empresariales.",description:"Automatiza la creación y gestión de estimados, facturas, propuestas, contratos y documentos de aprobación desde una plataforma sencilla.",features:["Estimados","Facturas","Propuestas","Contratos","Firmas electrónicas","Seguimiento de aprobaciones","Generación de PDF","Enlaces públicos para compartir"],ideal:["Empresas de servicios","Contratistas","Consultores","Agencias","Imprentas","Equipos de ventas"],cta:"Automatizar mis documentos",visual:"workflow-platform.png"},
{title:"Plataformas de reservas",subtitle:"Permite que tus clientes reserven y paguen online en cualquier momento.",description:"Un sistema profesional de reservas para administrar disponibilidad, citas, recordatorios, información de clientes y pagos online.",features:["Reservas online","Administración de calendario","Selección de servicios","Disponibilidad del personal","Recordatorios automáticos","Perfiles de clientes","Pagos online","Políticas de cancelación"],ideal:["Salones de belleza","Consultorios médicos","Coaches","Terapeutas","Consultores","Servicios a domicilio"],cta:"Crear mi sistema de reservas",visual:"order-management.png"},
{title:"Sistemas empresariales personalizados",subtitle:"Software diseñado alrededor de la forma en que opera tu empresa.",description:"Creamos plataformas personalizadas que conectan tus procesos, clientes, equipo y datos dentro de un sistema empresarial completo.",features:["Paneles personalizados","Roles de usuario","Automatización de procesos","Reportes y analíticas","Integración con CRM","Integración de pagos","Herramientas internas","Funciones con inteligencia artificial"],ideal:["Empresas en crecimiento","Negocios multiservicios","Imprentas","Empresas de construcción","Operaciones de comercio electrónico","Negocios con procesos únicos"],cta:"Crear mi sistema personalizado",visual:"crm-system.png"}]};
